version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Optionally build your docs in additional formats such as PDF
formats:
   - pdf

# Explicitly set the version of Python and its requirements
python:
  install:
    - requirements: docs/requirements.txt